import Link from "next/link";
import { adminUserQuerySchema } from "@/features/admin/user-schema";
import { getAdminSession } from "@/server/admin/auth";
import { adminUserService } from "@/server/admin-users";
import { formatCny } from "@/lib/money";

export default async function AdminUsersPage(props: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const query = adminUserQuerySchema.parse(await props.searchParams);
  const result = await adminUserService.list(await getAdminSession(), { ...query, pageSize: 20 });
  if (!result.ok) return null;
  const pages = Math.max(1, Math.ceil(result.data.total / 20));
  return <main><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm tracking-[0.2em] text-amber-800">用户运营</p><h1 className="mt-2 text-3xl font-semibold">用户与会员</h1></div><span className="text-sm text-stone-500">共 {result.data.total} 位用户</span></div><form className="mt-6 flex flex-wrap gap-3 rounded-2xl bg-white p-4"><input name="search" defaultValue={query.search} placeholder="搜索姓名或邮箱" className="min-w-56 flex-1 rounded-xl border border-stone-300 px-4 py-2" /><select name="role" defaultValue={query.role ?? ""} className="rounded-xl border border-stone-300 px-4 py-2"><option value="">全部角色</option><option value="USER">普通用户</option><option value="ADMIN">管理员</option></select><select name="status" defaultValue={query.status ?? ""} className="rounded-xl border border-stone-300 px-4 py-2"><option value="">全部状态</option><option value="ACTIVE">正常</option><option value="FROZEN">已冻结</option></select><button className="rounded-full bg-stone-800 px-5 py-2 text-white">筛选</button></form><div className="mt-6 overflow-x-auto rounded-3xl border border-stone-200 bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-stone-50 text-stone-500"><tr><th className="p-4">用户</th><th className="p-4">角色/状态</th><th className="p-4">会员等级</th><th className="p-4">累计实付</th><th className="p-4">订单数</th><th className="p-4 text-right">操作</th></tr></thead><tbody>{result.data.items.map((user) => <tr key={user.id} className="border-t border-stone-100"><td className="p-4"><p className="font-medium">{user.name}</p><p className="text-xs text-stone-400">{user.email}</p></td><td className="p-4">{user.role === "ADMIN" ? "管理员" : "普通用户"} · {user.status === "FROZEN" ? "已冻结" : "正常"}</td><td className="p-4">心悦 {user.membershipLevel}</td><td className="p-4">{formatCny(user.lifetimePaidCents)}</td><td className="p-4">{user.orderCount}</td><td className="p-4 text-right"><Link href={`/admin/users/${user.id}`} className="text-amber-800 hover:underline">查看详情</Link></td></tr>)}</tbody></table>{result.data.items.length === 0 ? <p className="p-12 text-center text-stone-500">没有符合条件的用户</p> : null}</div><p className="mt-5 text-right text-sm text-stone-500">第 {query.page} / {pages} 页</p></main>;
}
