"use client";
import { useActionState } from "react";
import { createAdminCategoryAction, setAdminCategoryStatusAction, updateAdminCategoryAction, type AdminCategoryActionState } from "@/app/actions/admin-category";
import type { AdminCategoryRecord } from "@/server/services/admin-category-service";
const initial: AdminCategoryActionState = { status: "IDLE", message: "" };
const inputClass = "rounded-xl border border-stone-300 px-3 py-2 text-sm outline-none focus:border-amber-700 disabled:bg-stone-100";
function NewCategoryForm() { const [state, action, pending] = useActionState(createAdminCategoryAction, initial); return <form action={action} className="grid gap-3 rounded-3xl border border-stone-200 bg-white p-5 md:grid-cols-2 xl:grid-cols-6"><input name="name" required maxLength={100} placeholder="分类名称" disabled={pending} className={inputClass} /><input name="slug" required maxLength={120} placeholder="category-slug" disabled={pending} className={inputClass} /><input name="description" maxLength={500} placeholder="分类描述（选填）" disabled={pending} className={`${inputClass} xl:col-span-2`} /><input name="sortOrder" type="number" min={0} defaultValue={0} disabled={pending} className={inputClass} /><input type="hidden" name="status" value="ACTIVE" /><button disabled={pending} className="rounded-full bg-stone-900 px-4 py-2 text-sm text-white">{pending ? "创建中…" : "新增分类"}</button><p className="text-xs text-rose-700 md:col-span-2 xl:col-span-6">{state.message}</p></form>; }
function CategoryRow({ category }: { category: AdminCategoryRecord }) { const [editState, editAction, editing] = useActionState(updateAdminCategoryAction, initial); const [statusState, statusAction, changing] = useActionState(setAdminCategoryStatusAction, initial); const nextStatus = category.status === "ACTIVE" ? "HIDDEN" : "ACTIVE"; return <article className="rounded-3xl border border-stone-200 bg-white p-5"><form action={editAction} className="grid gap-3 md:grid-cols-2 xl:grid-cols-[1fr_1fr_2fr_7rem_auto]"><input type="hidden" name="id" value={category.id} /><input name="name" required maxLength={100} defaultValue={category.name} disabled={editing || changing} className={inputClass} /><input name="slug" required maxLength={120} defaultValue={category.slug} disabled={editing || changing} className={inputClass} /><input name="description" maxLength={500} defaultValue={category.description} disabled={editing || changing} className={inputClass} /><input name="sortOrder" type="number" min={0} defaultValue={category.sortOrder} disabled={editing || changing} className={inputClass} /><input type="hidden" name="status" value={category.status} /><button disabled={editing || changing} className="rounded-full border border-stone-300 px-4 py-2 text-sm">{editing ? "保存中…" : "保存"}</button></form><div className="mt-3 flex flex-wrap items-center justify-between gap-3 text-sm"><span className="text-stone-500">{category.productCount} 个商品 · {category.status === "ACTIVE" ? "显示中" : "已隐藏"}</span><form action={statusAction}><input type="hidden" name="id" value={category.id} /><input type="hidden" name="status" value={nextStatus} /><button disabled={editing || changing} onClick={(event) => { if (nextStatus === "HIDDEN" && !window.confirm("确认隐藏此分类吗？分类下商品将不再公开展示。")) event.preventDefault(); }} className={nextStatus === "HIDDEN" ? "text-rose-700" : "text-emerald-700"}>{changing ? "处理中…" : nextStatus === "HIDDEN" ? "隐藏分类" : "恢复显示"}</button></form></div><p className={`mt-2 text-xs ${editState.status === "SUCCESS" || statusState.status === "SUCCESS" ? "text-emerald-700" : "text-rose-700"}`}>{statusState.message || editState.message}</p></article>; }
export function CategoryManager({ categories }: { categories: AdminCategoryRecord[] }) { return <div className="mt-8 space-y-4"><NewCategoryForm />{categories.map((category) => <CategoryRow key={category.id} category={category} />)}{categories.length === 0 ? <p className="rounded-3xl border border-dashed border-stone-300 p-12 text-center text-stone-500">暂无分类，请先新增</p> : null}</div>; }
