import "server-only";
import { and, asc, count, desc, eq, inArray, like, or } from "drizzle-orm";
import { db } from "@/db";
import { orderItems, orders, users } from "@/db/schema";
import type { MembershipLevel } from "@/lib/membership";
import type { AdminOrderRecord, AdminOrderRepository, AdminOrderCommandResult } from "@/server/services/admin-order-service";
const selection = { id: orders.id, orderNo: orders.orderNo, userId: orders.userId, userName: users.name, userEmail: users.email, status: orders.status, paymentStatus: orders.paymentStatus, membershipLevelSnapshot: orders.membershipLevelSnapshot, originalAmountCents: orders.originalAmountCents, discountRateBps: orders.discountRateBps, memberDiscountCents: orders.memberDiscountCents, shippingFeeCents: orders.shippingFeeCents, totalCents: orders.totalCents, recipientName: orders.recipientName, recipientPhone: orders.recipientPhone, recipientAddress: orders.recipientAddress, expiresAt: orders.expiresAt, paidAt: orders.paidAt, cancelledAt: orders.cancelledAt, shippedAt: orders.shippedAt, completedAt: orders.completedAt, createdAt: orders.createdAt, updatedAt: orders.updatedAt };
async function attachItems(rows: Array<Omit<AdminOrderRecord, "items" | "membershipLevelSnapshot"> & { membershipLevelSnapshot: number }>) {
  if (!rows.length) return [];
  const itemRows = await db.select({ orderId: orderItems.orderId, productId: orderItems.productId, productName: orderItems.productName, productCoverUrl: orderItems.productCoverUrl, unitPriceCents: orderItems.unitPriceCents, quantity: orderItems.quantity, subtotalCents: orderItems.subtotalCents }).from(orderItems).where(inArray(orderItems.orderId, rows.map((row) => row.id))).orderBy(asc(orderItems.id));
  const grouped = new Map<number, AdminOrderRecord["items"]>(); for (const item of itemRows) { const values = grouped.get(item.orderId) ?? []; values.push({ productId: item.productId, productName: item.productName, productCoverUrl: item.productCoverUrl, unitPriceCents: item.unitPriceCents, quantity: item.quantity, subtotalCents: item.subtotalCents }); grouped.set(item.orderId, values); }
  return rows.map((row) => ({ ...row, membershipLevelSnapshot: row.membershipLevelSnapshot as MembershipLevel, items: grouped.get(row.id) ?? [] }));
}
async function mapUpdate(result: { 0: { affectedRows: number } }, orderNo: string): Promise<AdminOrderCommandResult> { if (result[0].affectedRows === 1) return { status: "UPDATED" }; const [exists] = await db.select({ id: orders.id }).from(orders).where(eq(orders.orderNo, orderNo)).limit(1); return exists ? { status: "INVALID_STATE" } : { status: "NOT_FOUND" }; }
export const adminOrderRepository: AdminOrderRepository = {
  async list(input) { const conditions = []; if (input.search) conditions.push(or(like(orders.orderNo, `%${input.search}%`), like(users.name, `%${input.search}%`), like(users.email, `%${input.search}%`))!); if (input.status) conditions.push(eq(orders.status, input.status)); const where = conditions.length ? and(...conditions) : undefined; const [rows, [total]] = await Promise.all([db.select(selection).from(orders).innerJoin(users, eq(users.id, orders.userId)).where(where).orderBy(desc(orders.createdAt), desc(orders.id)).limit(input.pageSize).offset((input.page - 1) * input.pageSize), db.select({ value: count() }).from(orders).innerJoin(users, eq(users.id, orders.userId)).where(where)]); return { items: await attachItems(rows), total: total?.value ?? 0 }; },
  async getByOrderNo(orderNo) { const [row] = await db.select(selection).from(orders).innerJoin(users, eq(users.id, orders.userId)).where(eq(orders.orderNo, orderNo)).limit(1); if (!row) return null; return (await attachItems([row]))[0] ?? null; },
  async markShipped(input) { const result = await db.update(orders).set({ status: "SHIPPED", shippedAt: input.now, updatedAt: input.now }).where(and(eq(orders.orderNo, input.orderNo), eq(orders.status, "PAID"), eq(orders.paymentStatus, "SUCCESS"))); return mapUpdate(result, input.orderNo); },
  async markCompleted(input) { const result = await db.update(orders).set({ status: "COMPLETED", completedAt: input.now, updatedAt: input.now }).where(and(eq(orders.orderNo, input.orderNo), eq(orders.status, "SHIPPED"))); return mapUpdate(result, input.orderNo); },
};
