"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { parseAdminCategoryFormData } from "@/features/admin/category-schema";
import { getAdminSession } from "@/server/admin/auth";
import { adminCategoryService } from "@/server/admin-categories";
import { auditService } from "@/server/audit";
export type AdminCategoryActionState = { status: "IDLE" | "SUCCESS" | "ERROR"; message: string; fieldErrors?: Record<string, string[]> };
const fail = (message: string, fieldErrors?: Record<string, string[]>): AdminCategoryActionState => ({ status: "ERROR", message, fieldErrors });
const idSchema = z.coerce.number().int().positive();
function refresh() { revalidatePath("/admin/categories"); revalidatePath("/admin/products"); revalidatePath("/"); revalidatePath("/api/categories"); }
export async function createAdminCategoryAction(_state: AdminCategoryActionState, formData: FormData): Promise<AdminCategoryActionState> { const admin = await getAdminSession(); if (!admin) return fail("没有后台管理权限"); const parsed = parseAdminCategoryFormData(formData); if (!parsed.success) return fail("请检查分类信息", parsed.error.flatten().fieldErrors); try { const result = await adminCategoryService.create(admin, parsed.data); if (!result.ok) return fail(result.message); await auditService.record(admin, { action: "CATEGORY_CREATE", targetType: "CATEGORY", targetId: String(result.id), summary: `创建分类：${parsed.data.name}` }).catch(() => undefined); } catch (error) { console.error("创建分类失败", { error }); return fail("创建分类失败，请稍后重试"); } refresh(); return { status: "SUCCESS", message: "分类已创建" }; }
export async function updateAdminCategoryAction(_state: AdminCategoryActionState, formData: FormData): Promise<AdminCategoryActionState> { const admin = await getAdminSession(); if (!admin) return fail("没有后台管理权限"); const id = idSchema.safeParse(formData.get("id")); const parsed = parseAdminCategoryFormData(formData); if (!id.success || !parsed.success) return fail("请检查分类信息", parsed.success ? undefined : parsed.error.flatten().fieldErrors); try { const result = await adminCategoryService.update(admin, { id: id.data, data: parsed.data }); if (!result.ok) return fail(result.message); await auditService.record(admin, { action: "CATEGORY_UPDATE", targetType: "CATEGORY", targetId: String(id.data), summary: `更新分类：${parsed.data.name}` }).catch(() => undefined); } catch (error) { console.error("更新分类失败", { error }); return fail("更新分类失败，请稍后重试"); } refresh(); return { status: "SUCCESS", message: "分类已更新" }; }
export async function setAdminCategoryStatusAction(_state: AdminCategoryActionState, formData: FormData): Promise<AdminCategoryActionState> { const admin = await getAdminSession(); if (!admin) return fail("没有后台管理权限"); const parsed = z.object({ id: idSchema, status: z.enum(["ACTIVE", "HIDDEN"]) }).safeParse({ id: formData.get("id"), status: formData.get("status") }); if (!parsed.success) return fail("分类操作参数不正确"); try { const result = await adminCategoryService.setStatus(admin, parsed.data); if (!result.ok) return fail(result.message); await auditService.record(admin, { action: "CATEGORY_STATUS", targetType: "CATEGORY", targetId: String(parsed.data.id), summary: parsed.data.status === "HIDDEN" ? "隐藏分类" : "显示分类" }).catch(() => undefined); } catch (error) { console.error("更新分类状态失败", { error }); return fail("更新分类状态失败，请稍后重试"); } refresh(); return { status: "SUCCESS", message: parsed.data.status === "HIDDEN" ? "分类已隐藏" : "分类已显示" }; }
